# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "master" ]

jobs:    
	my-deploy:
      	runs-on: [self-hosted, linux]

	    strategy: 
            matrix:
                node-version: [16.x]

      	steps: 
         	- uses: actions/checkout@v2

         	- name: Use Node.js ${{ matrix.node-version }}
           	  uses: actions/setup-node@V1
			  with: 
				node-version: ${{ matrix.node-version }}

			- name: npm i and npm run build
			  run :
			    npm i
				mpm run build

			- name:  copy files to server
			  uses:  appleboy/scp-action@master
			  with:
			    HOST: ${{ secrets.HOST }}
				PORT: ${{ secrets.PORT }}
				USERNAME: ${{ secrets.USERNAME }}
				password: ${{ secrets.PASSWORD }}
				target: ${ secrets.TARGET }}
				source: "./dist/*"
				strip_components: 1
			    






  
