# This is a basic workflow to help you get started with Actions


name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: "Install & build"
        run: |
          npm i
          npm run build
          # mv public/index.html public/index.nginx-debian.html





			- name:  copy files to server
			  uses:  appleboy/scp-action@master
			  with:
			    host: ${{ secrets.HOST }}
					port: ${{ secrets.PORT }}
					username: ${{ secrets.USERNAME }}
					password: ${{ secrets.PASSWORD }}
					target: ${ secrets.TARGET }}
					source: "./dist/*"
					strip_components: 1
			    






  
