# This is a basic workflow to help you get started with Actions

name: Go Build

on:
  push:
    branches: [ master ]

jobs:

  build:    
		check-bats-version:
    runs-on: 
ded      group: [self-hosted, linux, ARM64]

    - name: Set up Go 1.x
      uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        node-version: [ 16.x ]

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Build
      run: |
          npm i
          npm run build

    - name: "Push to server"
        uses: appleboy/scp-action@master
			  with:
			    HOST: ${{ secrets.HOST }}
					PORT: ${{ secrets.PORT }}
					USERNAME: ${{ secrets.USERNAME }}
					PASSWORD: ${{ secrets.PASSWORD }}
					TARGET: ${ secrets.TARGET }}
					SOURCE: "./dist/*"
					strip_components: 1
			    






  
